FROM arm32v7/nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf

WORKDIR /usr/share/nginx/html
COPY dist/ .

COPY startFrontend.sh /usr/bin/startFrontend.sh

ENTRYPOINT ["/usr/bin/startFrontend.sh"]
