swagger: '2.0'
info:
  title: Pound API for Asterisk
  version: 0.0.1
  description: >-
    This document contains the specification for the Pound API that let's you
    view the call history from Asterisk.
basePath: /pound-api/v1
tags:
  - name: call
    description: Provides access to the call history.
schemes:
  - http
paths:
  '/calls':
    get:
      tags:
        - call
      summary: Returns all or filtered calls.
      description: ''
      operationId: getCalls
      produces:
        - application/json
      parameters:
        - name: disposition
          in: query
          description: >-
            Filter the result collection by providing a disposition type.
          type: string
          required: false
        - name: calldate
          in: query
          description: Show only calls never then the given date
          type: string
          format: date-time
        - name: offset
          in: query
          description: Paginate the result collection with the given offset.
          type: integer
          required: false
        - name: limit
          in: query
          description: Limits the result collection.
          type: integer
          required: false
      responses:
        '200':
          description: Successful operation.
          schema:
            title: Call list
            type: array
            items:
              $ref: '#/definitions/Call'
        '400':
          description: Bad Request - Invalid parameter value.
        '401':
          description: Unauthorized - No user credentials where provided.
        '404':
          description: Not Found - No result has been found matching the request criteria.
definitions:
  Call:
    type: object
    properties:
      calldate:
        type: string
        description: The calls start time
      src:
        type: string
        description: Call source
      dst:
        type: string
        description: Call destination
      duration:
        type: integer
        description: Call duration in seconds
      dcontext:
        type: string
        description: Asterisk context used for this call
      disposition:
        type: string
        description: Call disposition
    xml:
      name: Call
    example:
      calldate: '2018-06-30 15:30:59'
      src: '0123456789'
      dst: '+49123987654'
      duration: 352
      dcontext: public-out
      disposition: ANSWERED
